# Generated by Django 2.2.6 on 2019-11-24 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0002_auto_20191124_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coche',
            name='fotoCoche',
        ),
        migrations.CreateModel(
            name='FotoCoche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoCoche', models.ImageField(default='images/None/no-img.jpg', upload_to='static/img/coche')),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOutletCar.Coche')),
            ],
        ),
    ]
