# Generated by Django 3.0 on 2019-12-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0004_auto_20191207_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodecoche',
            options={'ordering': ['nombre']},
        ),
    ]
